---
abstract: 'a tree-based versatile config handler'
author:
  - 'Dominik Schulz <dominik.schulz@gauner.org>'
build_requires:
  FindBin: 0
  Test::MockObject::Universal: 0
  Test::More: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Yak
requires:
  Config::Any: 0
  Config::Tiny: 0
  Data::Dumper: 0
  Data::Tree: 0
  English: 0
  Hash::Merge: 0
  IO::Handle: 0
  Log::Tree::RequiredLogger: 0
  Module::Pluggable::Object: 0
  Moose: 0
  Moose::Role: 0
  Scalar::Util: 0
  Try::Tiny: 0
  autodie: 0
  feature: 0
  mro: 0
  namespace::autoclean: 0
  perl: 5.010_000
  warnings: 0
resources:
  bugtracker: https://github.com/gittex/Config-Yak/issues
  repository: git://github.com/gittex/Config-Yak.git
version: 0.22
x_authority: cpan:TEX
